tasks:
  - name: NextJS Frontend
    init: cd nextjs-frontend && yarn
    command: yarn run dev
  - name: Discord Bot Backend
    init: cd python-discord-bot && pip install -r requirements.txt
    command: python bot.py

ports:
  - name: Open Me!
    port: 3000
    onOpen: open-browser
    visibility: public