# fly.toml app configuration file generated for guildist-nextjs-frontend on 2023-05-29T15:07:02Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "guildist-nextjs-frontend"
primary_region = "lhr"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
